### ISSUE TITLE
UnhandledPromiseRejectionWarning preventing stream from being delivered to iOS device

### ISSUE THREAD

**Issue by swagman925** [hjdhjd/homebridge-unifi-protect#100]
**Describe The Problem:**
All looks good until I try to view the live video. It doesn't deliver stream to device.

**To Reproduce:**
View stream on iOS/macOS/tvOS device.

**Logs:**

```
UniFi Protect] Davidson NVR [UCK-G2-PLUS]: A doorbell has been detected. Setting the controller refresh interval to 2 seconds.
9/22/2020, 8:17:31 PM (node:1434) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
9/22/2020, 8:17:31 PM at RTPStreamManagement.generateSetupEndpointResponse (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/camera/RTPStreamManagement.js:688:98)
9/22/2020, 8:17:31 PM at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/camera/RTPStreamManagement.js:657:27
9/22/2020, 8:17:31 PM at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/once.js:16:25
9/22/2020, 8:17:31 PM at ProtectStreamingDelegate.prepareStream (/home/hoobs/.hoobs/node_modules/homebridge-unifi-protect/dist/protect-stream.js:142:9)
9/22/2020, 8:17:31 PM at processTicksAndRejections (internal/process/task_queues.js:97:5)
9/22/2020, 8:17:31 PM (node:1434) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
9/22/2020, 8:17:31 PM (node:1434) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Homebridge Configuration:**

```json
{
            "platform": "UniFi Protect",
            "plugin_map": {
                "plugin_name": "homebridge-unifi-protect"
            },
            "controllers": [
                {
                    "address": "x.x.x.x",
                    "username": "hoobs",
                    "password": "*******"
                }
            ],
            "motionDuration": 10,
            "verboseFfmpeg": true,
            "options": [
                "Enable.StreamOnly.Medium",
                "Enable.ContactSensor"
            ],
        }
```

**Screenshots:**

**Environment:**

* **Homebridge Version**: Hoobs v3.2.6
* **Node Version**: 12.18.1
* **Homebridge UniFi Protect Version**: 12.18.1
* **Apple Device and iOS / macOS / iPadOS / tvOS Version**: MacBook Pro 2019 (macOS 10.15.6), iPhone 11 Pro Max (iOS 14)
* **Operating System and OS Version**: Debian 10
* **UniFi Camera**: UVC-G4-DoorBell

**Comment by hjdhjd** [comment]
Sorry you’re having an issue. Unfortunately, this is a bug in HOOBS, not this plugin.

HOOBS needs to be updated to incorporate the latest Homebridge API updates. The HOOBS developers are aware, but you may want to reach out and add your vote for pushing out the update sooner than later. I know they’re working on it.

You can downgrade to an older version of homebridge-unifi-protect, before 3.6.0, that is still compatible with the older API that HOOBS uses.

Good luck.
