### ISSUE TITLE
UVC PRO camera error since 4.0.0

### ISSUE THREAD

**Issue by pratsenka** [hjdhjd/homebridge-unifi-protect#224]
**Describe The Problem:**
UVC PRO camera seems doesn't work with this plugin since 4.0.0 version (3.7.9 was the latest "good") thought G3 and G3 PRO cameras do
I do not see UVC PRO camera in HomeKit though plugin says it is discovered. 

**Logs:**
```
(node:9310) UnhandledPromiseRejectionWarning: RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 65535. Received 4294967295
    at checkInt (internal/buffer.js:69:11)
    at writeU_Int16LE (internal/buffer.js:719:3)
    at Buffer.writeUInt16LE (internal/buffer.js:727:10)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1199:13
    at Array.forEach (<anonymous>)
    at RTPStreamManagement._supportedVideoStreamConfiguration (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:1190:30)
    at new RTPStreamManagement (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:516:51)
    at CameraController.constructServices (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/controller/CameraController.ts:196:41)
    at Accessory.configureController (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:620:31)
    at PlatformAccessory.configureController (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:136:34)
    at ProtectCamera.configureVideoStream (/usr/lib/node_modules/homebridge-unifi-protect/src/protect-camera.ts:605:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:9310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```
**Homebridge Configuration:**

No specific configuration, just address and credentials

**Environment:**

* **Homebridge Version:** 1.1.7
* **Node Version:** v14.15.3
* **Homebridge-UniFi-Protect Plugin Version:** 3.7.9 (works with UVC PRO, 4.0.0-4.3.0 doesn't)
* **UniFi Protect Controller Version:** initially 1.13.7 now upgraded to 1.16.9
* **UniFi Protect Controller Type:** UCKgen2+
* **Operating System and OS Version:** Ubuntu

**Comment by hjdhjd** [comment]
Thanks for the report. Don't have a UVC Pro to test with, but it should work if Protect picks it up. One thing I noticed is you're running this on a UCK. As of homebridge-unifi-protect v4.3.0, the minimum required firmware for UCK is v2.0.24. Try upgrading to the latest and see if it makes a difference.

Changelog:
https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/Changelog.md#430-2020-12-26

**Comment by pratsenka** [comment]
Yes, I have upgraded to 2.0.24 before reporting an issue. Initially I had 0.9.7 firmware with 1.13.7 Unifi Protect.
I've got 5 cams (UVC PRO, G3 and G3 PRO) and all of them are discovered by plugin though UVC PRO stopped working. I have to disable it via Disable.MAC option to get rid of logging errors every 10 seconds

**Comment by hjdhjd** [comment]
Thanks for the info. Is the above a complete encapsulation of the errors that get repeated?

**Comment by hjdhjd** [comment]
Also...please post the list of RTSP resolutions for your UVC Pro. You can find it by going into the Protect webUI, clicking on the camera, going to Manage, and seeing what's under the RTSP block. Looking to see what the values are for Low | Medium | High. Thanks!

**Comment by pratsenka** [comment]
There are just High and Low, no Medium. Maybe this is a problem?

**Comment by hjdhjd** [comment]
Not necessarily. What are the resolutions listed for each?

**Comment by pratsenka** [comment]
High (1920x1080)
Low (640x360)

**Comment by hjdhjd** [comment]
@pratsenka I haven't forgotten about you. :smile: Happy new year!

Can you try to force a stream quality on the camera? Use this feature option: 

`Enable.Video.Stream.Only.Low`

If that works, you can try enabling High only, instead.

Let me know how that works...I'm going to take a closer look over the weekend as well. Would appreciate you trying the above and letting me know. Thanks!

**Comment by pratsenka** [comment]
Happy New Year!

Here are log lines:
---
[37m[1/2/2021, 10:27:23 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 4294967295x4294967295@255fps => 4294967295x4294967295@255fps (Medium).
[37m[1/2/2021, 10:27:23 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 3840x2160@30fps => 4294967295x4294967295@255fps (Medium).
[37m[1/2/2021, 10:27:23 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 1920x1080@30fps => 4294967295x4294967295@255fps (Medium).
[37m[1/2/2021, 10:27:23 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 1280x720@30fps => 4294967295x4294967295@255fps (Medium).
[37m[1/2/2021, 10:27:23 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 640x360@10fps => 640x360@10fps (Low).
[37m[1/2/2021, 10:27:23 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 320x240@15fps => 640x360@10fps (Low).
---
I also tried to set Enable.Video.Stream.Only.Low earlier but it didn't help. Now this option doesn't work either

**Comment by hjdhjd** [comment]
Thanks! Can you post a screenshot of the Protect webUI under the Manage tab where the RTSP section is?

Much appreciated.

**Comment by pratsenka** [comment]
![image](https://user-images.githubusercontent.com/65272916/103454088-5ada0900-4cf1-11eb-9053-2f4d707b6c4f.png)

**Comment by hjdhjd** [comment]
Please activate both streams, restart the plugin, and post the resolution mapping. Thanks!

**Comment by pratsenka** [comment]
if I enable High resolution for this cam log lines will be:
---
[37m[1/2/2021, 11:57:57 AM] [39m[36m[Google Smart Home] [39mFinished instance discovery
[37m[1/2/2021, 11:58:03 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 4294967295x4294967295@255fps => 4294967295x4294967295@255fps (Medium).
[37m[1/2/2021, 11:58:03 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 3840x2160@30fps => 4294967295x4294967295@255fps (Medium).
[37m[1/2/2021, 11:58:03 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 1920x1080@30fps => 1920x1080@25fps (High).
[37m[1/2/2021, 11:58:03 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 1920x1080@25fps => 1920x1080@25fps (High).
[37m[1/2/2021, 11:58:03 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 1280x720@30fps => 4294967295x4294967295@255fps (Medium).
[37m[1/2/2021, 11:58:03 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 640x360@10fps => 640x360@10fps (Low).
[37m[1/2/2021, 11:58:03 AM] [39m[36m[UniFi Protect] [39mEye [UCK-G2-PLUS] UVC Pro [UVC Pro]: Mapping resolution: 320x240@15fps => 640x360@10fps (Low).
---

**Comment by hjdhjd** [comment]
Please try v4.3.5 - should fix the issue. Thanks!

**Comment by pratsenka** [comment]
It works!

Thank you!

**Comment by hjdhjd** [comment]
Thanks for reporting it and working with me on identifying the core issue.
