### ISSUE TITLE
Homebridge Crash when using plugin 

### ISSUE THREAD

**Issue by NorthernMan54** [hjdhjd/homebridge-unifi-protect#610]
We are working thru an issue triggered by a recent change to an upstream dependency of MQTT that is triggering this message when more than one plugin in a runtime is using an older version of MQTT - see mqttjs/MQTT.js#1388

To resolve this issue for @smhex reported here - https://github.com/arachnetech/homebridge-mqttthing/issues/518

Can you update the MQTT dependency to the latest version, 4.3.2 ?

[12/30/2021, 3:02:15 PM] [ShellyTemp] Initializing mqttthing accessory... [12/30/2021, 3:02:15 PM] RangeError: Maximum call stack size exceeded at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) at Function.Array.from (/homebridge/node_modules/homebridge-mqttthing/node_modules/collections/shim-array.js:35:22) [12/30/2021, 3:02:15 PM] Got SIGTERM, shutting down Homebridge...

**Describe The Problem:**

**To Reproduce:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Configuration:**

```json
Show the relevant portion of your homebridge config.json here, if needed.
Remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** 
* **Node Version:** 
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 
* **UniFi Protect Controller Type:** 
* **UniFi Protect Controller Firmware Version:** 
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:**

**Comment by hjdhjd** [comment]
Oh joy. I’ll pin the MQTT version, same as what @Sunoo did and push an update out later today. Thanks @NorthernMan54.

**Comment by Sunoo** [comment]
@hjdhjd The latest mqtt version supposedly fixes the issue too, though I haven’t switched to it yet.

**Comment by NorthernMan54** [comment]
Tks Very much

PS The user who reported the issue updated the version updated the version and reported success.  So you should be good
