### ISSUE TITLE
Crashes HB

### ISSUE THREAD

**Issue by tablatronix** [hjdhjd/homebridge-unifi-protect#685]
**Describe The Problem:**
Crashes homebridge

**To Reproduce:**

homebridge-unifi-protect v5.5.0
Unifi protect 1.21.2

**Logs:**

```php
[2/24/2022, 3:31:14 PM] TypeError: Cannot read properties of undefined (reading 'hksv')
    at WebSocket.nvrApi.eventsWs.on.updatesListener (/homebridge/node_modules/homebridge-unifi-protect/src/protect-nvr-events.ts:246:37)
    at WebSocket.emit (node:events:520:28)
    at Receiver.receiverOnMessage (/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/websocket.js:1137:20)
    at Receiver.emit (node:events:520:28)
    at Receiver.dataMessage (/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/receiver.js:513:14)
    at Receiver.getData (/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
[2/24/2022, 3:31:14 PM] Got SIGTERM, shutting down Homebridge...
```
**Homebridge Configuration:**

not much 
```json

        {
            "controllers": [
                {
                    "address": "192.168.100.3",
                    "password": "*****",
                    "username": "SVC_homebridge"
                }
            ],
            "verboseFfmpeg": true,
            "platform": "UniFi Protect"
        },
```

**Screenshots:**
![Screen Shot 2022-02-24 at 3 50 38 PM](https://user-images.githubusercontent.com/807787/155613636-f1bdc290-a251-4ab4-83c7-82aaf90ad856.png)
**Environment:**

* **Homebridge Version:** 1.4.0
* **Node Version:** 16.14.0
* **Homebridge-UniFi-Protect Plugin Version:**
* **UniFi Protect Version:** 1.21.2
* **UniFi Protect Controller Type:**CKII

* **Operating System and OS Version:** <!-- Raspbian / docker

**Comment by hjdhjd** [comment]
Thanks...what Protect devices do you have? Can you paste the relevant portion of the logs that show what devices it detects on startup?

Good bug finding!

**Comment by tablatronix** [comment]
Sure thing
hmm no logs in my logs directory.. Is that something I need to enable?

**Comment by tablatronix** [comment]
```php

[2/24/2022, 4:11:12 PM] Loaded plugin: homebridge-unifi-protect@5.5.0
[2/24/2022, 4:11:12 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[2/24/2022, 4:11:13 PM] [UniFi Protect] Initializing UniFi Protect platform...
[2/24/2022, 4:11:13 PM] [UniFi Protect] Verbose logging of video streaming sessions enabled. Expect a lot of data.
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS]: Connected to the UniFi Protect controller API (address: 192.168.100.3 mac: E063DA206EC7).
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS]: The user 'SVC_homebridge' requires the Administrator role in order to automatically configure camera RTSP streams.
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS]: Connected to the UniFi Protect realtime update events API.
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS]: Discovered camera: Kitchen [UVC G3 Micro] (address: 192.168.100.79 mac: B4FBE47E7723).
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS]: Discovered camera: Front Yard [UVC G3 Flex] (address: 192.168.100.93 mac: 7483C23F72B6).
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS]: Discovered camera: Back Yard [UVC G3 Instant] (address: 192.168.100.98 mac: 74ACB99E1D65).
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS]: Controller refresh interval set to 10 seconds.
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS] Kitchen [UVC G3 Micro]: HomeKit Secure Video support enabled.
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS] Front Yard [UVC G3 Flex]: HomeKit Secure Video support enabled.
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS] Back Yard [UVC G3 Instant]: HomeKit Secure Video support enabled.
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS] Kitchen [UVC G3 Micro]: No RTSP stream profiles have been configured for this camera. Enable at least one RTSP stream profile in the UniFi Protect webUI to resolve this issue or assign the Administrator role to the user configured for this plugin to allow it to automatically configure itself.
[2/24/2022, 4:11:15 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS] Front Yard [UVC G3 Flex]: No RTSP stream profiles have been configured for this camera. Enable at least one RTSP stream profile in the UniFi Protect webUI to resolve this issue or assign the Administrator role to the user configured for this plugin to allow it to automatically configure itself.
[2/24/2022, 4:11:25 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS] Kitchen [UVC G3 Micro]: No RTSP stream profiles have been configured for this camera. Enable at least one RTSP stream profile in the UniFi Protect webUI to resolve this issue or assign the Administrator role to the user configured for this plugin to allow it to automatically configure itself.
[2/24/2022, 4:11:25 PM] [UniFi Protect] UniFi Cloud Key Gen2 Plus [UCK-G2-PLUS] Front Yard [UVC G3 Flex]: No RTSP stream profiles have been configured for this camera. Enable at least one RTSP stream profile in the UniFi Protect webUI to resolve this issue or assign the Administrator role to the user configured for this plugin to allow it to automatically configure itself.
```

**Comment by tablatronix** [comment]
It was crashing HB constantly for days, now its not...
 lol Perhaps its some kind of notification or alert?

I am logging and will try to catch it again

**Comment by hjdhjd** [comment]
Thanks...I got it from here. 😄 Appreciated!

**Comment by tablatronix** [comment]
Is a patch expected for this? Closed means identified, can i workaround it , crashes are back

**Comment by hjdhjd** [comment]
An update will be coming when it’s ready. No timeline beyond that…this work happens in my infinite spare time. :)

You can always revert to an earlier versions of the plugin. Thanks.
