### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Fodolan** [hjdhjd/homebridge-unifi-protect#775]
**Describe The Problem:**
I have a fresh install of Homebridge 1.5.0 with Node.js 16.16.0 on a Raspberry Pi B+.
I am trying to install UniFi Protect plugin. I don't have other plugin.

**To Reproduce:**
Select "Homebridge Unifi Protect" and clic "INSTALLER" in Plugins section.

**Logs:**
...
840 timing reifyNode:node_modules/homebridge-unifi-protect/node_modules/mqtt Completed in 219980ms
841 timing reifyNode:node_modules/homebridge-unifi-protect/node_modules/js-sdsl Completed in 223839ms
842 timing reifyNode:node_modules/homebridge-unifi-protect/node_modules/es-abstract Completed in 335682ms
843 timing reifyNode:node_modules/homebridge-unifi-protect/node_modules/rxjs Completed in 443824ms
844 timing reify:unpack Completed in 444654ms
845 timing reify:rollback:createSparse Completed in 36181ms
846 timing reify:rollback:retireShallow Completed in 1ms
847 timing command:install Completed in 614600ms
848 verbose stack Error: process terminated
848 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:198:39
848 verbose stack     at process.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
848 verbose stack     at process.emit (node:events:539:35)
849 verbose cwd /var/lib/homebridge
850 verbose Linux 5.15.32+
851 verbose node v16.16.0
852 verbose npm  v8.11.0
853 error process terminated
854 error signal SIGTERM
855 verbose exit 1
856 timing npm Completed in 619595ms
857 verbose unfinished npm timer reify 1659169050916
858 verbose code 1
859 error A complete log of this run can be found in:
859 error     /home/jean-luc/.npm/_logs/2022-07-30T08_17_25_999Z-debug-0.log

**Environment:**

* **Homebridge Version:** 1.5.0
* **Node Version:** 16.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 5.5.4
* **Operating System and OS Version:** Raspbian

**Comment by Fodolan** [comment]
I was able to install in SSH with the same command. Don't understand but it's work...
