### ISSUE TITLE
Homebridge Crashing Every Few Minutes

### ISSUE THREAD

**Issue by dead-beef-cafe** [hjdhjd/homebridge-unifi-protect#779]
**Describe The Problem:**
Homebridge will crash and restart every few minutes.

**To Reproduce:**
Seems to be semi-random. Opening or closing a steam - particularly the Doorbell stream - seems the most likely action to trigger it but it does not happen every time.

I am using a non-administrator unifi protect user and I have unifi's smart motion events turned off, if that makes a difference.

**Logs:**
```
 TypeError: Cannot read properties of undefined (reading 'hksv')
    at WebSocket.nvrApi.eventsWs.on.updatesListener (/var/lib/homebridge/node_modules/homebridge-unifi-protect/src/protect-nvr-events.ts:246:37)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/var/lib/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/websocket.js:1169:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/var/lib/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/receiver.js:513:14)
    at Receiver.getData (/var/lib/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/var/lib/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/var/lib/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)

```
**Homebridge Configuration:**
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "",
        "port": 51192,
        "pin": "",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "10.0.1.9",
                    "password": "",
                    "username": ""
                }
            ],
            "options": [
                "Disable.Doorbell.Messages"
            ],
            "platform": "UniFi Protect"
        }
    ]
}
```

**Screenshots:**
![IMG_1764](https://user-images.githubusercontent.com/37557891/184554964-f6732124-de63-41a3-8c75-e30225d54320.jpeg)

**Environment:**
Homebridge Version: 1.5.0
Node Version: 16.16.0
Homebridge-UniFi-Protect Plugin Version: 5.5.4
Operating System and OS Version: Ubuntu Jammy Jellyfish (22.04.1 LTS)

**Comment by hjdhjd** [comment]
Sorry - not much I can help with on this one. I'd suggest potentially uninstalling and reinstalling the plugin as a starting point, and/or reinstalling the latest production firmware on Protect as firmware updates, especially in the 2.x series, have been rocky on the Ubiquiti end.

Best of luck. Curious if you get this one resolved.
