### ISSUE TITLE
NodeJS Error in 3.7.0

### ISSUE THREAD

**Issue by ccutrer** [hjdhjd/homebridge-unifi-protect#89]
```
(node:1617) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'debugAll' of undefined
    at ProtectDoorbell.debug (/homebridge/node_modules/homebridge-unifi-protect/src/protect-platform.ts:135:20)
    at new RtpSplitter (/homebridge/node_modules/homebridge-unifi-protect/src/protect-rtp.ts:70:10)
    at ProtectStreamingDelegate.prepareStream (/homebridge/node_modules/homebridge-unifi-protect/src/protect-stream.ts:174:7)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by hjdhjd** [comment]
Thanks. More context...did you do anything to generate the error?

**Comment by hjdhjd** [comment]
Try v3.7.1. Thanks.

**Comment by ccutrer** [comment]
Yup it's fixed.

**Comment by ccutrer** [comment]
Gah nope, it happened again on 3.7.1 when opening the video stream in the Home app:

```
(node:4164) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'debugAll' of undefined
    at ProtectDoorbell.debug (/homebridge/node_modules/homebridge-unifi-protect/src/protect-platform.ts:135:20)
    at new RtpSplitter (/homebridge/node_modules/homebridge-unifi-protect/src/protect-rtp.ts:70:10)
    at ProtectStreamingDelegate.prepareStream (/homebridge/node_modules/homebridge-unifi-protect/src/protect-stream.ts:174:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by hjdhjd** [comment]
Fixed for real this time. Sorry about that...it's just plain embarrassing.

**Comment by ccutrer** [comment]
Noope. Still happening with 3.7.2.

**Comment by hjdhjd** [comment]
Post your config.json and details of your configuration. Something else is going on. I don't have this error.

**Comment by hjdhjd** [comment]
Standby. I just recreated it...finally.

**Comment by ccutrer** [comment]
```{
    "bridge": {
        "name": "Homebridge 4512",
        "username": "0E:83:9A:C3:45:12",
        "port": 53443,
        "pin": "<redacted>"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8081,
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "192.168.85.1",
                    "mqttUrl": "mqtts://homebridge-unifi-protect:<redacted>@mqtt.cutrer.network/",
                    "password": "<redacted>",
                    "username": "homebridge"
                }
            ],
            "platform": "UniFi Protect"
        }
  ]
}
```

A UDM Pro, a Doorbell, and that's it.

**Comment by hjdhjd** [comment]
I got it.

**Comment by hjdhjd** [comment]
Try v3.7.3. Fixed for real. Again - embarrassing.
