### ISSUE TITLE
6.0 crashing on getSnapshot (for disabled camera?)

### ISSUE THREAD

**Issue by jmissig** [hjdhjd/homebridge-unifi-protect#901]
Hey, thanks as always for this excellent homebridge plugin. It’s amazing how much you’ve made Protect feel like a HomeKit product!

**Describe The Problem:**
6.0 seems to be crashing on `getSnapshot` for me, which I _assume_ is happening on cameras that I have disabled. My Protect homebridge account is intentionally not administrator, logs complain about lack of RTSP streams on disabled cameras.

**To Reproduce:**

- Updated to 6.0.
- Went through the visual config to disable certain cameras and doorbell which I do not want to appear in HomeKit.
- Homebridge account on Protect is _not_ an administrator and therefore cannot set a doorbell message or change RTSP config for existing cameras.
- The enabled cameras have RTSP streams enabled, and are the same as the enabled cameras in v5.x.y.
- The disabled cameras are the same as were disabled in v5.x.y.

**Logs:**

```
[3/26/2023, 10:22:09 PM] [homebridge-unifi-protect] Launched child bridge with PID 3846
[3/26/2023, 10:22:09 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[3/26/2023, 10:22:09 PM] [homebridge-unifi-protect] Loaded homebridge-unifi-protect v6.0.1 child bridge successfully
[3/26/2023, 10:22:09 PM] Loaded 7 cached accessories from cachedAccessories.CCxxxxxxxx35.
[3/26/2023, 10:22:09 PM] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-unifi-protect) is running on port 38267.
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] Connected to the UniFi Protect API at 172.16.1.1.
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM [UDM-PRO]: The user 'homebridge' requires the Administrator role in order to automatically configure camera RTSP streams.
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM: Discovered nvr: 1812 UDM [UDM Pro] (address: 172.16.1.1 mac: 74xxxxxxxx81).
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM: Discovered camera: Living Room [G3 Micro] (address: 172.16.1.223 mac: F0xxxxxxxxB3).
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM: Discovered camera: Carport [G4 Bullet] (address: 172.16.1.221 mac: D0xxxxxxxxA8).
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM: Discovered camera: North Gate [G3 Bullet] (address: 172.16.1.222 mac: 80xxxxxxxx18).
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM: Discovered camera: South Gate [G3 Bullet] (address: 172.16.1.227 mac: 80xxxxxxxxE9).
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM: Discovered camera: North Patio [G3 Pro] (address: 172.16.1.226 mac: B4xxxxxxxx10).
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM: Discovered camera: Driveway [G4 Bullet] (address: 172.16.1.224 mac: 74xxxxxxxxEB).
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM: Discovered camera: South Walkway [G3 Flex] (address: 172.16.1.225 mac: FCxxxxxxxxA0).
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM: Unable to set the default doorbell message. Please ensure this username has the Administrator role in UniFi Protect.
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM [UDM-PRO] Living Room [G3 Micro]: No RTSP stream profiles have been configured for this camera. Enable at least one RTSP stream profile in the UniFi Protect webUI to resolve this issue or assign the Administrator role to the user configured for this plugin to allow it to automatically configure itself.
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM [UDM-PRO] South Gate [G3 Bullet]: No RTSP stream profiles have been configured for this camera. Enable at least one RTSP stream profile in the UniFi Protect webUI to resolve this issue or assign the Administrator role to the user configured for this plugin to allow it to automatically configure itself.
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM [UDM-PRO] North Patio [G3 Pro]: No RTSP stream profiles have been configured for this camera. Enable at least one RTSP stream profile in the UniFi Protect webUI to resolve this issue or assign the Administrator role to the user configured for this plugin to allow it to automatically configure itself.
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] 1812 UDM [UDM-PRO] South Walkway [G3 Flex]: No RTSP stream profiles have been configured for this camera. Enable at least one RTSP stream profile in the UniFi Protect webUI to resolve this issue or assign the Administrator role to the user configured for this plugin to allow it to automatically configure itself.
TypeError: Cannot read properties of undefined (reading 'getSnapshot')
    at ProtectCamera.configureSnapshotUpdates (file:///home/nodejs/node_modules/lib/node_modules/homebridge-unifi-protect/src/protect-camera.ts:715:25)
    at ProtectCamera.configureDevice (file:///home/nodejs/node_modules/lib/node_modules/homebridge-unifi-protect/src/protect-camera.ts:146:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] Child bridge process ended
[3/26/2023, 10:22:10 PM] [homebridge-unifi-protect] Process Ended. Code: 1, Signal: null
```

**Homebridge Configuration:**

```json
{
    "controllers": [
        {
            "address": "172.16.1.1",
            "password": "[redacted]",
            "username": "homebridge"
        }
    ],
    "options": [
        "Disable.B4xxxxxxxx10",
        "Disable.F0xxxxxxxxB3",
        "Disable.FCxxxxxxxxA0",
        "Disable.80xxxxxxxxE9",
        "Disable.Doorbell.Messages.74xxxxxxxx81",
        "Disable.Doorbell.Messages.D0xxxxxxxxA8",
        "Disable.Doorbell.Messages.74xxxxxxxxEB",
        "Disable.Doorbell.Messages.F0xxxxxxxxB3",
        "Disable.Doorbell.Messages.80xxxxxxxx18",
        "Disable.Doorbell.Messages.B4xxxxxxxx10",
        "Disable.Doorbell.Messages.80xxxxxxxxE9",
        "Disable.Doorbell.Messages.FCxxxxxxxxA0",
        "Disable.Device.F0xxxxxxxxB3",
        "Disable.Device.B4xxxxxxxx10",
        "Disable.Device.80xxxxxxxxE9",
        "Disable.Device.FCxxxxxxxxA0",
        "Disable.Doorbell.Messages.FromDoorbell.74xxxxxxxx81",
        "Disable.Log.Doorbell.74xxxxxxxx81"
    ],
    "_bridge": {
        "username": "CC:xxxxxxxx:35"
    },
    "platform": "UniFi Protect"
}
```

**Environment:**

* **Homebridge Version:** v1.6.0
* **Node Version:** v18.15.0
* **Homebridge-UniFi-Protect Plugin Version:** v6.0.1
* **UniFi Protect Version:** 2.2.11
* **UniFi Protect Controller Type:** UDM-Pro
* **UniFi Protect Controller Firmware Version:** UniFi OS 2.5.17
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** n/a bug happens before getting to launch Home
* **Operating System and OS Version:** Ubuntu 22.04.2

**Comment by hjdhjd** [comment]
Thanks for the report. I’ll address this in the next release.

Also noteworthy: feature options have changed. Disabling a device/camera in HBUP is now Disable.Device.MACAddress rather than Disable.MACAddress. 

That said…a bug is a bug. 😄 

Thanks for the report.

**Comment by jmissig** [comment]
Yep, saw that in the release notes! Left Disable.MACAddress there for comparison — I assume the Disable.Device.MACAddress ones were added by the web UI when I went through that config. On Mar 27, 2023, at 00:05, hjdhjd ***@***.***> wrote:﻿
Thanks for the report. I’ll address this in the next release.
Also noteworthy: feature options have changed. Disabling a device/camera in HBUP is now Disable.Device.MACAddress rather than Disable.MACAddress.
That said…a bug is a bug. 😄
Thanks for the report.

**Comment by hjdhjd** [comment]
That’s correct.

Once configured, if you restart Homebridge, out of curiosity, will it still crash out? Or just the first time you restart?

I’m trying to tighten a reproducible use case that I’ll test when I’m more awake…

**Comment by jmissig** [comment]
Oh good question, it’s running fine since all of Homebridge has restarted. I get the error about the doorbell message but it’s running.

The homebridge-unifi-protect child bridge was repeatedly restarting, so I downgraded to v5.5.4 and then reported this bug. I just updated back to v6.0.1 and everything’s running w/o crash.

**Comment by jmissig** [comment]
To be super clear: Crashed until all of Homebridge restarted. Now it doesn’t crash. So, not as big a deal as I originally thought.

Didn’t realize child bridge restarts weren’t sufficient for some of the config things / caches / whatnot. Today I learned.

**Comment by hjdhjd** [comment]
That's correct. Alright...thanks for validating I'm not nuts. 😄 At least not for this one. Whew. Closing this - feel free to open a new issue if this comes back. Sound good?

**Comment by hjdhjd** [comment]
Made things a bit more robust for edge cases like this in v6.0.2. Thanks again for the report.
