### ISSUE TITLE
Crash soon after streaming start on G3 Micro

### ISSUE THREAD

**Issue by AndrewMorsillo** [hjdhjd/homebridge-unifi-protect#93]
**Describe The Problem:**
First of all, thanks for building this awesome plugin! 

Plugin crashes taking homebridge with it after a few seconds of streaming g3 micro

Somehow `this.config` becomes `undefined` in `protect-platform.ts` when calling `debug`.... which doesn't make sense. It's clearly initialized.

```
[9/18/2020, 12:58:43 PM] [UniFi Protect] home [UCK-G2-PLUS] Nursery  [UVC G3 Micro]: HomeKit video stream request received: 1280x720, 30 fps, 299 kbps.
[9/18/2020, 12:59:01 PM] TypeError: Cannot read property 'debugAll' of undefined
    at ProtectCamera.debug (C:\dev\tools\nvm\v12.18.3\node_modules\homebridge-unifi-protect\src\protect-platform.ts:135:20)
    at ProtectStreamingDelegate.handleStreamRequest (C:\dev\tools\nvm\v12.18.3\node_modules\homebridge-unifi-protect\src\protect-stream.ts:488:14)
    at RTPStreamManagement.handleReconfigureStream (C:\dev\tools\nvm\v12.18.3\node_modules\homebridge\node_modules\hap-nodejs\src\lib\camera\RTPStreamManagement.ts:833:19)
    at RTPStreamManagement._handleSelectedStreamConfigurationWrite (C:\dev\tools\nvm\v12.18.3\node_modules\homebridge\node_modules\hap-nodejs\src\lib\camera\RTPStreamManagement.ts:635:14)
    at Characteristic.emit (events.js:315:20)
    at Characteristic.EventEmitter.emit (C:\dev\tools\nvm\v12.18.3\node_modules\homebridge\node_modules\hap-nodejs\src\lib\EventEmitter.ts:42:22)
    at Characteristic._this.setValue (C:\dev\tools\nvm\v12.18.3\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Characteristic.ts:652:12)
    at C:\dev\tools\nvm\v12.18.3\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:1461:24
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleSetCharacteristics (C:\dev\tools\nvm\v12.18.3\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:1303:10)
```

**To Reproduce:**
Install via config-ui-x, configure, start streaming g3 micro

**Logs:**
see above

**Homebridge Configuration:**

```json
   {
            "controllers": [
                {
                    "address": "192.168.1.xxx",
                    "password": "mypassword",
                    "username": "myusername"
                }
            ],
            "platform": "UniFi Protect"
        }
```

**Screenshots:**
N/A

**Environment:**

* **Homebridge Version**: 1.2.2
* **Homebridge UniFi Protect Version**: 3.7.4
* **Operating System and OS Version**: Win 10

**Comment by hjdhjd** [comment]
You mean it's not supposed to crash when you try to use it? 😄 

Thanks, I know the problem. Standby.

**Comment by hjdhjd** [comment]
What version of Node are you running, out of curiosity?

**Comment by hjdhjd** [comment]
This will be fixed in 3.7.5 coming soon to a homebridge near you.

**Comment by hjdhjd** [comment]
v3.7.5 is out. Sorry about that. Enjoy.

**Comment by AndrewMorsillo** [comment]
Works great now, thanks!
