### ISSUE TITLE
Can't get plugin to work after update

### ISSUE THREAD

**Issue by delim888** [hjdhjd/homebridge-unifi-protect#936]
**Describe The Problem:**
Can't get plugin to work, Homebridge installed on CloudKey itself, all was working fine until updated plugin to 6.5.1, tried to delete user->reboot->add new user->reboot->set privileges
Tried to install 6.5.0 back, no success

**To Reproduce:**

**Logs:**

```
[5/10/2023, 6:54:23 PM] Homebridge v1.6.1 (HAP v0.11.1) (UCK Homebridge) is running on port 51866.
[5/10/2023, 6:54:24 PM] [UCK UniFi Protect] Launched child bridge with PID 24858
[5/10/2023, 6:54:24 PM] [UCK Shelly OG] Launched child bridge with PID 24859
[5/10/2023, 6:54:24 PM] [UCK Shelly NG] Launched child bridge with PID 24865
[5/10/2023, 6:54:24 PM] Registering platform 'homebridge-shelly-ng.ShellyNG'
[5/10/2023, 6:54:24 PM] [UCK Shelly NG] Loaded homebridge-shelly-ng v1.6.0 child bridge successfully
[5/10/2023, 6:54:24 PM] Loaded 0 cached accessories from cachedAccessories.0E43BD43046A.
[5/10/2023, 6:54:24 PM] Homebridge v1.6.1 (HAP v0.11.1) (UCK Shelly NG) is running on port 32917.
[5/10/2023, 6:54:24 PM] [UCK Shelly NG] mDNS device discovery started
[5/10/2023, 6:54:25 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[5/10/2023, 6:54:25 PM] [UCK UniFi Protect] Loaded homebridge-unifi-protect v6.5.1 child bridge successfully
[5/10/2023, 6:54:25 PM] Homebridge v1.6.1 (HAP v0.11.1) (UCK UniFi Protect) is running on port 48102.
[5/10/2023, 6:54:25 PM] Registering platform 'homebridge-shelly.Shelly'
[5/10/2023, 6:54:25 PM] [UCK Shelly OG] Loaded homebridge-shelly v0.19.1 child bridge successfully
[5/10/2023, 6:54:25 PM] Loaded 10 cached accessories from cachedAccessories.0E2B3693C41A.
[5/10/2023, 6:54:25 PM] [UCK Shelly OG] 10 accessories loaded from cache
[5/10/2023, 6:54:25 PM] Homebridge v1.6.1 (HAP v0.11.1) (UCK Shelly OG) is running on port 59341.
[5/10/2023, 6:54:25 PM] [UCK Shelly OG] Admin server is running on port 8181
(node:24858) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
[5/10/2023, 7:19:43 PM] [Homebridge UI] [homebridge-unifi-protect] Terminating child process...
[5/10/2023, 7:19:43 PM] [Homebridge UI] [homebridge-unifi-protect] Child process ended
[5/10/2023, 7:22:11 PM] [Homebridge UI] [homebridge-unifi-protect] Terminating child process...
[5/10/2023, 7:22:12 PM] [Homebridge UI] [homebridge-unifi-protect] node:events:491
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:400:5)
    at target.send (node:internal/child_process:740:16)
    at PluginUiServer.ready (/var/lib/homebridge/node_modules/homebridge-unifi-protect/node_modules/@homebridge/plugin-ui-utils/dist/server.js:105:17)
    at new PluginUiServer (file:///var/lib/homebridge/node_modules/homebridge-unifi-protect/homebridge-ui/server.js:162:10)
    at file:///var/lib/homebridge/node_modules/homebridge-unifi-protect/homebridge-ui/server.js:166:8
    at file:///var/lib/homebridge/node_modules/homebridge-unifi-protect/homebridge-ui/server.js:166:29
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
Emitted 'error' event on process instance at:
    at node:internal/child_process:744:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}

Node.js v18.13.0
[5/10/2023, 7:22:12 PM] [Homebridge UI] [homebridge-unifi-protect] Child process ended
[5/10/2023, 7:22:50 PM] [Homebridge UI] [homebridge-unifi-protect] Terminating child process...
[5/10/2023, 7:22:50 PM] [Homebridge UI] [homebridge-unifi-protect] Child process ended
```

**Homebridge Configuration:**

```json

            "controllers": [
                {
                    "address": "192.168.198.2",
                    "password": "homebridgeuserA1",
                    "username": "homebridgeuser"
                },
                {
                    "address": "127.0.0.1",
                    "password": "homebridgeuserA1",
                    "username": "homebridgeuser"
                },
                {
                    "address": "localhost",
                    "password": "homebridgeuserA1",
                    "username": "homebridgeuser"
                }
            ],
            "name": "UCK UniFi Protect",
            "options": [
                "Enable.Video.Stream.Only.High",
                "Enable.Video.HKSV.Record.Only.High"
            ],
            "platform": "UniFi Protect",
            "_bridge": {
                "username": "REDACTED",
                "port": 48102
            }
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.6.1
* **Node Version:** v18.13.0
* **Homebridge-UniFi-Protect Plugin Version:** v6.5.1
* **UniFi Protect Version:** 2.7.34
* **UniFi Protect Controller Type:** UCKgen2+
* **UniFi Protect Controller Firmware Version:** 3.0.17
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:**
* **Operating System and OS Version:** Debian 11

**Comment by hjdhjd** [comment]
Give v6.6.0 a go...appreciate the bug report and I'm curious to see if the error persists. How did you get Homebridge running on UniFi OS 3? I've got a spare UCK and can try to duplicate your setup as well.

**Comment by hjdhjd** [comment]
Hmm. I'll take a closer look. What's the last working version? You can always revert back using the Homebridge webUI.

**Comment by delim888** [comment]
Tried to downgrade, now no version of plugin works:(

and strange log of 6.6.0, no errors at all
![IMG_7092](https://github.com/hjdhjd/homebridge-unifi-protect/assets/36953091/bafa9946-df7d-4bae-b742-bad7688c700b)

**Comment by hjdhjd** [comment]
I installed it successfully on a UCK using the link you shared. I’d suggest deleting the Homebridge install and starting fresh. I suspect this is an issue with the Homebridge installation, not HBUP. Give that a try.

**Comment by delim888** [comment]
> I installed it successfully on a UCK using the link you shared. I’d suggest deleting the Homebridge install and starting fresh. I suspect this is an issue with the Homebridge installation, not HBUP. Give that a try.

What's your UCK firmware?

Just tried following:
1) Put UCK to recovery mode, reset to factory settings, applied latest stable firmware from https://www.ui.com/download/unifi/unifi-cloud-key-gen2
2) After reboot setup in like a new device, turned on ssh, turned off AutoUpdates for UniFi OS and Applications
3) Remove Network App and updated Protect to latest 2.7.34 version, added homebridge local user and set privileges
4) Via terminal applied update & upgrade, reboot, installed Homebridge via:
https://github.com/homebridge/homebridge-apt-pkg
5) Customized Systemd service to run as root, and allow the UI to shutdown/restart the host
6) logged to freshly installed Homebridge, added user, installed Protect plugin 6.6.0, added controller: address: localhost, user: homebridge
7) Restart service
8) No errors in log, and still no connection to controller :(

**Comment by delim888** [comment]
[5/16/2023, 6:39:43 PM] Homebridge v1.6.1 (HAP v0.11.1) (UCK Homebridge) is running on port 51866.
[5/16/2023, 6:39:45 PM] [UCK UniFi Protect] Launched child bridge with PID 23804
[5/16/2023, 6:39:45 PM] Registering platform 'homebridge-unifi-protect.UniFi Protect'
[5/16/2023, 6:39:45 PM] [UCK UniFi Protect] Loaded homebridge-unifi-protect v6.6.0 child bridge successfully
[5/16/2023, 6:39:45 PM] Homebridge v1.6.1 (HAP v0.11.1) (UCK UniFi Protect) is running on port 48102.
[5/16/2023, 6:40:05 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[5/16/2023, 6:40:11 PM] [Homebridge UI] [homebridge-unifi-protect] Incoming Request: /getDevices
[5/16/2023, 6:40:27 PM] [Homebridge UI] [homebridge-unifi-protect] Terminating child process...
[5/16/2023, 6:40:27 PM] [Homebridge UI] [homebridge-unifi-protect] Child process ended
[5/16/2023, 6:45:47 PM] [Homebridge UI] [homebridge-unifi-protect] Terminating child process...
[5/16/2023, 6:45:47 PM] [Homebridge UI] [homebridge-unifi-protect] Child process ended

Just terminated :)

**Comment by delim888** [comment]
Found my old RPI, with HB 1.5.1, installed plugin and it connects to controller, strange thing

**Comment by delim888** [comment]
Have a good sign, installed from scratch 3.0.13 UnifiOS, updated Protect, Homebridge, Plugin to latest versions, now im able to connect to controller via hostname stated in the left panel of Homebridge main screen, but I can't connect via 127.0.0.1, localhost, or IP
will now update to 3.0.17 and check

**Comment by delim888** [comment]
So identified problem, when I set hostname provided by UniFi OS to plug-in settings all seems to work ok, but when I use IP of controller or 127.0.0.1 or localhost, nothing works

**Comment by hjdhjd** [comment]
Glad you got things going and you're up and running. And thanks for the tip about HBUP on a UCK...going to have to play with it a bit more.
