### ISSUE TITLE
UniFi G4 Pro

### ISSUE THREAD

**Issue by MomoDAwesome** [hjdhjd/homebridge-unifi-protect#947]
**Describe The Problem:**
 Just setup a G4 Pro and only the package camera is showing in HomeBridge and HomeKit. I am also unable to directly view the package camera in HomeKit.

**To Reproduce:**

**Logs:**
 [5/31/2023, 6:51:02 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: Streaming request from 192.168.1.14: 1280x720@30fps, 299 kbps. Using Package Camera, 800 kbps.
[5/31/2023, 6:51:02 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: FFmpeg process ended unexpectedly with an exit code of 1.
[5/31/2023, 6:51:02 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: FFmpeg command line that errored out was: /var/lib/homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -nostats -fflags +discardcorrupt -probesize 32768 -max_delay 500000 -r 2 -rtsp_transport tcp -i rtsps://192.168.1.1:7441/null?enableSrtp -map 0:v:0 -vcodec copy -payload_type 99 -ssrc 14712236 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params T1rjM4Mr2R3Ia6bfuwNdXuqbhHSDgNEBViATs22t srtp://192.168.1.14:61764?rtcpport=61764&pkt_size=564 -map 0:a:0? -acodec libfdk_aac -afterburner 1 -eld_sbr 1 -eld_v2 1 -profile:a 38 -flags +global_header -f null -ar 24k -b:a 24k -bufsize 48k -ac 1 -payload_type 110 -ssrc 12835749 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params jFaLGl/gAgG/+yA1sTV3OstNz7qDhWb6siYjFW+n srtp://192.168.1.14:65209?rtcpport=65209&pkt_size=188
[5/31/2023, 6:51:02 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: [tls @ 0x5580a4a1a440] IO error: End of file
[5/31/2023, 6:51:02 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: rtsps://192.168.1.1:7441/null?enableSrtp: Invalid data found when processing input
[5/31/2023, 6:51:02 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: Stopped video streaming session.
[5/31/2023, 6:51:02 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: Error in communicating with the return audio channel: Error: WebSocket was closed before the connection was established
    at WebSocket.terminate (/var/lib/homebridge/node_modules/homebridge-unifi-protect/node_modules/ws/lib/websocket.js:481:7)
    at ProtectStreamingDelegate.startStream (file:///var/lib/homebridge/node_modules/homebridge-unifi-protect/src/protect-stream.ts:789:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ProtectStreamingDelegate.handleStreamRequest (file:///var/lib/homebridge/node_modules/homebridge-unifi-protect/src/protect-stream.ts:844:9)
[5/31/2023, 8:36:40 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: Streaming request from 192.168.1.93: 1280x720@30fps, 299 kbps. Using Package Camera, 800 kbps.
[5/31/2023, 8:36:40 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: FFmpeg process ended unexpectedly with an exit code of 1.
[5/31/2023, 8:36:40 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: FFmpeg command line that errored out was: /var/lib/homebridge/node_modules/homebridge-unifi-protect/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -nostats -fflags +discardcorrupt -probesize 32768 -max_delay 500000 -r 2 -rtsp_transport tcp -i rtsps://192.168.1.1:7441/null?enableSrtp -map 0:v:0 -vcodec copy -payload_type 99 -ssrc 1100899 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params RM6uU7Tvc3V3qx4vnLeiqIkJykCzN4B5rYR6Yyqx srtp://192.168.1.93:50656?rtcpport=50656&pkt_size=564 -map 0:a:0? -acodec libfdk_aac -afterburner 1 -eld_sbr 1 -eld_v2 1 -profile:a 38 -flags +global_header -f null -ar 24k -b:a 24k -bufsize 48k -ac 1 -payload_type 110 -ssrc 8933704 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params BUwjoJpi1IwOtiMY9MhME+JJAl7lm2nQ+aMib/gR srtp://192.168.1.93:57449?rtcpport=57449&pkt_size=188
[5/31/2023, 8:36:40 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: [tls @ 0x561721759440] IO error: End of file
[5/31/2023, 8:36:40 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: rtsps://192.168.1.1:7441/null?enableSrtp: Invalid data found when processing input
[5/31/2023, 8:36:40 AM] [homebridge-unifi-protect] TsDream [UDM-PRO] Front Door  Package Camera [G4 Doorbell Pro]: Stopped video streaming session.

**Homebridge Configuration:**

**Screenshots:**

![IMG_1025](https://github.com/hjdhjd/homebridge-unifi-protect/assets/108203899/3ae58d6b-f3fe-4059-8c31-418764aa405f)

**Environment:**

* **Homebridge Version:** 1.6.1
* **Node Version:** 18.16.0
* **Homebridge-UniFi-Protect Plugin Version:** 6.7.0
* **UniFi Protect Version:** 2.7.34
* **UniFi Protect Controller Type:**  UDMP
* **UniFi Protect Controller Firmware Version:**  3.0.20
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** 16.4.1 (a)
* **Operating System and OS Version:**  Ubuntu Jammy Jellyfish (22.04.2 LTS)

**Comment by MomoDAwesome** [comment]
Comment to keep ticket alive
