### ISSUE TITLE
API error: Unable to connect to the Protect controller (UDM-SE)

### ISSUE THREAD

**Issue by SemoTech** [hjdhjd/homebridge-unifi-protect#994]
**Describe The Problem:**
homebridge-unifi-protect plugin unable to talk to UDM-SE and connect.  All was working fine before. Now log is filled with same API error.  Restating homebridge or the entire machine does not help. 

**To Reproduce:**
Restart homebridge, check homebridge logs

**Logs:**
```
[homebridge-unifi-protect] 192.168.1.2: API error: Unable to connect to the Protect controller. This is usually temporary and will occur during Protect controller reboots and firmware updates.
```

**Homebridge Configuration:**

```json
{            
       "controllers": [
                {
                    "address": "192.168.1.2",
                    "name": "UDM Protect",
                    "password": "udmpassword",
                    "username": "homebridgeudmuser"
                }
            ],
            "options": [
                "Enable.Doorbell.Trigger",
                "Enable.Doorbell.PhysicalChime.71A43AB4A831",
                "Enable.Device.StatusLed.71A43AB4A831",
                "Enable.Video.Stream.Only.Medium.71A43AB4A831",
                "Enable.Video.Transcode.Hardware.71A43AB4A831",
                "Enable.Video.HKSV.Record.Only.High.71A43AB4A831",
                "Enable.Device.SyncName.71A43AB4A831",
                "Enable.Doorbell.PhysicalChime.Duration.Digital.71A43AB4A831.10000",
                "Enable.Doorbell.Trigger.71A43AB4A831"
            ],
            "ringDuration": 3,
            "verboseFfmpeg": false,
            "_bridge": {
                "username": "0A:27:4F:E0:9B:2A",
                "port": 53734
            },
            "platform": "UniFi Protect"
        },
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.6.1 
* **Node Version:** v18.18.0 
* **Homebridge-UniFi-Protect Plugin Version:** v6.15.0 
* **UniFi Protect Version:** v2.8.35
* **UniFi Protect Controller Type:** UDM-SE
* **UniFi Protect Controller Firmware Version:** v3.1.16
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** Mac Pro MacOS 12.7 Montereay
* **Operating System and OS Version:** Docker on Ubuntu Server 22.04

**Comment by SemoTech** [comment]
Issue seems to be with the UDM itself as using a diferent login username/password seems to work.  Strangely even deleting and re-creating the original username, even using a new password for the re-created username still fails.  Maybe the UDM is blacklisting the username itself???

**Comment by hjdhjd** [comment]
It isn’t…this is a bug in the controller firmware and not an HBUP issue I’m afraid. You can reboot the controller, or wait until UI fixes it…there’s not much more to do for the moment. Thanks and best of luck.

**Comment by SemoTech** [comment]
> It isn’t…this is a bug in the controller firmware and not an HBUP issue I’m afraid. You can reboot the controller, or wait until UI fixes it…there’s not much more to do for the moment. Thanks and best of luck.

Thanks @hjdhjd I will reboot the UDM-SE tomorrow, as I am now getting a lot of other weird errors in the log.  Hope they go away:

```
[10/6/2023, 10:54:54 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Unable to retrieve a snapshot.
[10/6/2023, 10:54:54 PM] [UniFi Protect] 192.168.1.2 G3i Driveway [G3 Instant]: Unable to retrieve a snapshot.
[10/6/2023, 10:54:54 PM] [UniFi Protect] 192.168.1.2 G4i Kitchen [G4 Instant]: Unable to retrieve a snapshot.
[10/6/2023, 10:54:54 PM] [UniFi Protect] 192.168.1.2 G3i Game Room [G3 Instant]: Unable to retrieve a snapshot.
[10/6/2023, 10:54:57 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Unable to open the return audio channel.
[10/6/2023, 10:54:58 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Streaming request from 192.168.1.28: 640x480@30fps, 164 kbps. Using 960x720@30fps (Medium), 1,200 kbps.
[10/6/2023, 10:55:03 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Stopped video streaming session.
[10/6/2023, 10:55:03 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Unable to configure HomeKit Secure Video event recording support: unable to connect to the livestream API on the Protect controller.
[10/6/2023, 10:55:17 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Unable to open the return audio channel.
[10/6/2023, 10:55:18 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Streaming request from 192.168.1.28: 640x480@30fps, 164 kbps. Using 960x720@30fps (Medium), 1,200 kbps.
[10/6/2023, 10:55:22 PM] [UniFi Protect] 192.168.1.2 G3i Game Room [G3 Instant]: Unable to retrieve a snapshot.
[10/6/2023, 10:55:22 PM] [UniFi Protect] 192.168.1.2 G3i Driveway [G3 Instant]: Unable to retrieve a snapshot.
[10/6/2023, 10:55:22 PM] [UniFi Protect] 192.168.1.2 G4i Kitchen [G4 Instant]: Unable to retrieve a snapshot.
[10/6/2023, 10:55:23 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Stopped video streaming session.
[10/6/2023, 10:55:23 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Unable to configure HomeKit Secure Video event recording support: unable to connect to the livestream API on the Protect controller.
[10/6/2023, 10:55:24 PM] [UniFi Protect] 192.168.1.2 G3i Driveway [G3 Instant]: Unable to open the return audio channel.
[10/6/2023, 10:55:25 PM] [UniFi Protect] 192.168.1.2 G3i Driveway [G3 Instant]: Streaming request from 192.168.1.28: 1280x720@30fps, 299 kbps. Using 1024x576@30fps (Medium), 1,200 kbps.
[10/6/2023, 10:55:27 PM] [UniFi Protect] 192.168.1.2 G3i Driveway [G3 Instant]: The FFmpeg process ended unexpectedly due to issues with the media stream provided by the UniFi Protect livestream API. Adjusting the settings we use for FFmpeg temporarily to use safer values at the expense of some additional streaming startup latency.
[10/6/2023, 10:55:27 PM] [UniFi Protect] 192.168.1.2 G3i Driveway [G3 Instant]: Stopped video streaming session.
[10/6/2023, 10:55:27 PM] [UniFi Protect] 192.168.1.2 G3i Driveway [G3 Instant]: Unable to configure HomeKit Secure Video event recording support: unable to connect to the livestream API on the Protect controller.
[10/6/2023, 10:55:27 PM] [UniFi Protect] 192.168.1.2 G3i Driveway [G3 Instant]: Unable to configure HomeKit Secure Video event recording support: unable to connect to the livestream API on the Protect controller.
[10/6/2023, 10:55:37 PM] [UniFi Protect] 192.168.1.2 G3i Game Room [G3 Instant]: Unable to retrieve a snapshot.
[10/6/2023, 10:55:37 PM] [UniFi Protect] 192.168.1.2 G4i Kitchen [G4 Instant]: Unable to retrieve a snapshot.
[10/6/2023, 10:55:37 PM] [UniFi Protect] 192.168.1.2 G4 Doorbell Pro [G4 Doorbell Pro]: Unable to retrieve a snapshot.
[10/6/2023, 10:55:38 PM] [UniFi Protect] 192.168.1.2 G3i Driveway [G3 Instant]: Unable to retrieve a snapshot.
[10/6/2023, 10:56:04 PM] [UniFi Protect] [UDM-PRO-SE] G3f Patio [G3 Flex]: Unable to configure HomeKit Secure Video event recording support: the camera is not currently connected to the Protect controller. HomeKit Secure Video event recording will resume once the camera reconnects to the Protect controller.
[HDS 192.168.1.27] Encountered unexpected error on already closed recording stream 1: TypeError: Cannot read properties of null (reading 'stop')
    at ProtectRecordingDelegate.startTransmitting (file:///homebridge/node_modules/homebridge-unifi-protect/src/protect-record.ts:329:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ProtectRecordingDelegate.handleRecordingStreamRequest (file:///homebridge/node_modules/homebridge-unifi-protect/src/protect-record.ts:154:74)
```
